/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "ccnx_Portal.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_ccnx_api_ccnx_1Portal_CcnxPortal_ccnxPortal_1Create(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  CCNxPortalAttributes *arg1 = (CCNxPortalAttributes *) 0 ;
  CCNxPortalStack *arg2 = (CCNxPortalStack *) 0 ;
  CCNxPortal *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxPortalAttributes **)&jarg1; 
  arg2 = *(CCNxPortalStack **)&jarg2; 
  result = (CCNxPortal *)ccnxPortal_Create((CCNxPortalAttributes const *)arg1,(CCNxPortalStack const *)arg2);
  *(CCNxPortal **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_api_ccnx_1Portal_CcnxPortal_ccnxPortal_1Acquire(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CCNxPortal *arg1 = (CCNxPortal *) 0 ;
  CCNxPortal *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxPortal **)&jarg1; 
  result = (CCNxPortal *)ccnxPortal_Acquire((struct ccnx_portal const *)arg1);
  *(CCNxPortal **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ccnx_api_ccnx_1Portal_CcnxPortal_ccnxPortal_1Release(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  CCNxPortal **arg1 = (CCNxPortal **) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxPortal ***)&jarg1; 
  ccnxPortal_Release(arg1);
}


SWIGEXPORT jlong JNICALL Java_ccnx_api_ccnx_1Portal_CcnxPortal_ccnxPortal_1GetStatus(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CCNxPortal *arg1 = (CCNxPortal *) 0 ;
  CCNxPortalStatus *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxPortal **)&jarg1; 
  result = (CCNxPortalStatus *)ccnxPortal_GetStatus((struct ccnx_portal const *)arg1);
  *(CCNxPortalStatus **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ccnx_api_ccnx_1Portal_CcnxPortal_ccnxPortal_1GetFileId(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  CCNxPortal *arg1 = (CCNxPortal *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxPortal **)&jarg1; 
  result = (int)ccnxPortal_GetFileId((struct ccnx_portal const *)arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_api_ccnx_1Portal_CcnxPortal_ccnxPortal_1SetAttributes(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jboolean jresult = 0 ;
  CCNxPortal *arg1 = (CCNxPortal *) 0 ;
  CCNxPortalAttributes *arg2 = (CCNxPortalAttributes *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxPortal **)&jarg1; 
  arg2 = *(CCNxPortalAttributes **)&jarg2; 
  result = (bool)ccnxPortal_SetAttributes(arg1,(CCNxPortalAttributes const *)arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_api_ccnx_1Portal_CcnxPortal_ccnxPortal_1Listen(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  jboolean jresult = 0 ;
  CCNxPortal *arg1 = (CCNxPortal *) 0 ;
  CCNxName *arg2 = (CCNxName *) 0 ;
  time_t arg3 ;
  CCNxStackTimeout *arg4 = (CCNxStackTimeout *) 0 ;
  time_t const *argp3 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxPortal **)&jarg1; 
  arg2 = *(CCNxName **)&jarg2; 
  argp3 = *(time_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null time_t const");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = *(CCNxStackTimeout **)&jarg4; 
  result = (bool)ccnxPortal_Listen(arg1,(CCNxName const *)arg2,arg3,(CCNxStackTimeout const *)arg4);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_api_ccnx_1Portal_CcnxPortal_ccnxPortal_1Ignore(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jboolean jresult = 0 ;
  CCNxPortal *arg1 = (CCNxPortal *) 0 ;
  CCNxName *arg2 = (CCNxName *) 0 ;
  CCNxStackTimeout *arg3 = (CCNxStackTimeout *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxPortal **)&jarg1; 
  arg2 = *(CCNxName **)&jarg2; 
  arg3 = *(CCNxStackTimeout **)&jarg3; 
  result = (bool)ccnxPortal_Ignore(arg1,(CCNxName const *)arg2,(CCNxStackTimeout const *)arg3);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_api_ccnx_1Portal_CcnxPortal_ccnxPortal_1Send(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jboolean jresult = 0 ;
  CCNxPortal *arg1 = (CCNxPortal *) 0 ;
  CCNxMetaMessage *arg2 = (CCNxMetaMessage *) 0 ;
  CCNxStackTimeout *arg3 = (CCNxStackTimeout *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxPortal **)&jarg1; 
  arg2 = *(CCNxMetaMessage **)&jarg2; 
  arg3 = *(CCNxStackTimeout **)&jarg3; 
  result = (bool)ccnxPortal_Send(arg1,(CCNxMetaMessage const *)arg2,(CCNxStackTimeout const *)arg3);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_api_ccnx_1Portal_CcnxPortal_ccnxPortal_1Receive(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  CCNxPortal *arg1 = (CCNxPortal *) 0 ;
  CCNxStackTimeout *arg2 = (CCNxStackTimeout *) 0 ;
  CCNxMetaMessage *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxPortal **)&jarg1; 
  arg2 = *(CCNxStackTimeout **)&jarg2; 
  result = (CCNxMetaMessage *)ccnxPortal_Receive(arg1,(CCNxStackTimeout const *)arg2);
  *(CCNxMetaMessage **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_api_ccnx_1Portal_CcnxPortal_ccnxPortal_1GetKeyId(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CCNxPortal *arg1 = (CCNxPortal *) 0 ;
  PARCKeyId *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxPortal **)&jarg1; 
  result = (PARCKeyId *)ccnxPortal_GetKeyId((struct ccnx_portal const *)arg1);
  *(PARCKeyId **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_api_ccnx_1Portal_CcnxPortal_ccnxPortal_1IsEOF(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jboolean jresult = 0 ;
  CCNxPortal *arg1 = (CCNxPortal *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxPortal **)&jarg1; 
  result = (bool)ccnxPortal_IsEOF((struct ccnx_portal const *)arg1);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_api_ccnx_1Portal_CcnxPortal_ccnxPortal_1IsError(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jboolean jresult = 0 ;
  CCNxPortal *arg1 = (CCNxPortal *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxPortal **)&jarg1; 
  result = (bool)ccnxPortal_IsError((struct ccnx_portal const *)arg1);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ccnx_api_ccnx_1Portal_CcnxPortal_ccnxPortal_1GetError(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  CCNxPortal *arg1 = (CCNxPortal *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxPortal **)&jarg1; 
  result = (int)ccnxPortal_GetError((struct ccnx_portal const *)arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_api_ccnx_1Portal_CcnxPortal_ccnxPortal_1Flush(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jboolean jresult = 0 ;
  CCNxPortal *arg1 = (CCNxPortal *) 0 ;
  CCNxStackTimeout *arg2 = (CCNxStackTimeout *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxPortal **)&jarg1; 
  arg2 = *(CCNxStackTimeout **)&jarg2; 
  result = (bool)ccnxPortal_Flush(arg1,(CCNxStackTimeout const *)arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_api_ccnx_1Portal_CcnxPortal_ccnxPortal_1Send1(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jboolean jresult = 0 ;
  CCNxPortal *arg1 = (CCNxPortal *) 0 ;
  CCNxMetaMessage *arg2 = (CCNxMetaMessage *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxPortal **)&jarg1; 
  arg2 = *(CCNxMetaMessage **)&jarg2; 
  result = (bool)ccnxPortal_Send(arg1,(CCNxMetaMessage const *)arg2, CCNxStackTimeout_Never);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_api_ccnx_1Portal_CcnxPortal_ccnxPortal_1Receive1(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CCNxPortal *arg1 = (CCNxPortal *) 0 ;
  CCNxMetaMessage *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxPortal **)&jarg1; 
  result = (CCNxMetaMessage *)ccnxPortal_Receive(arg1, CCNxStackTimeout_Never);
  *(CCNxMetaMessage **)&jresult = result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

